version: "3.8"

services:
  homeoffice-calendar-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres
    restart: always

  postgres:
    image: postgres:12.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8082:8080
    environment:
      URL: openapi/Openapi.yml
    volumes:
      - ./docs:/usr/share/nginx/html/openapi
